#' plot_residuals
#'
#' Plots the histogram of the observed residuals and the corresponding normal density
#'
#' This function gets the residuals from the reg object and extracts mean and
#' standard deviation therefrom. It then plots a hastogram of the observed
#' residuals of the regression. It overlays the histogram with the curve of
#' a normal density with the mean and standard deviation of the residuals.
#'
#' @param reg
#'
#' @return plot A reg object generated by lm()
#' @export
#'
#' @examples
#' plot_residuals(reg)

plot_residuals <- function(reg) {
  resid <- reg$residuals                          ## store the residuals
  hist(resid, breaks=20, probability=TRUE)        ## Histogram with relative frequencies
  curve(dnorm(x, mean=mean(resid), sd=sd(resid)),   ## normal density curve with same mean and std.dev
        col="darkblue", lwd=2, add=TRUE)          ## in blue, linewidth = 2, overlay
}
